version: "3.2"

services:
  postgres:
    image: postgres:11.1-alpine
    expose:
      - 5432
    env_file:
      - .env

  app:
    build: .
    command: npm start
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
